---
namespace: aramirol
name: linux
description: Simple linux roles collections for testing
version: 1.0.4
authors:
  - Angel Ramiro

readme: README.md
repository: https://github.com/aramirol/ansible-collection-linux
issues: https://github.com/aramirol/ansible-collection-linux/issues
documentation: https://github.com/aramirol/ansible-collection-linux/blob/main/README.md
homepage: https://github.com/aramirol/ansible-collection-linux
license_file: LICENSE
license: []

dependencies:
  community.general: '>=1.0.0,!=3.3.0'
  community.docker: '>=1.0.0'

tags:
  - linux
  - system
  - collection
  - virtualization
  - containers
  
build_ignore:
  - .ansible-lint
  - .cache
  - .github
  - .gitignore
  - .yamllint
  - molecule
  - requirements.txt
