---
name: lxd

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 0'
  push:
    paths:
      - 'roles/lxd/**'
      - 'molecule/lxd/**'
      - '.github/workflows/role_lxd.yml'
  pull_request:
    paths:
      - 'roles/lxd/**'
      - 'molecule/lxd/**'
      - '.github/workflows/role_lxd.yml'

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      ansible: ${{ steps.set-matrix.outputs.ansible }}
      distro: ${{ steps.set-matrix.outputs.distro }}
      include: ${{ steps.set-matrix.outputs.include }}
      exclude: ${{ steps.set-matrix.outputs.exclude }}
    steps:
      - uses: actions/checkout@v2
      - name: Set matrix outputs
        id: set-matrix
        run: |
          include=$(jq -c .${{ github.workflow }}.include .github/matrix.json)
          [[ "$include" == "null" ]] && include=$(jq -c .include .github/matrix.json)
          echo "::set-output name=ansible::`jq -c .ansible .github/matrix.json`"
          echo "::set-output name=distro::`jq -c .distro .github/matrix.json`"
          echo "::set-output name=include::$include"
          echo "::set-output name=exclude::`jq -c '.${{ github.workflow }}.exclude // []' .github/matrix.json`"
